### ISSUE TITLE
Dependecy failures

### ISSUE THREAD

**Issue by cmwylie19** [mt-sre/managed-tenants-cli#276]
I am having errors during usage of the `managedtenants` cli.  Yesterday, for example, i had been using the managed tenants cli all day, then suddenly I got this error which I have been unable to recover from since.

Last week, while using the managed tenants cli i got a similar error and my debugging ended up removing critical python dependencies on my computer which resulted in me having to get a loaner which i am on now.

I do not use python ever, so it  am more perplex as to why these failures keep happening while I am attempting to use the tool.

Now on a loaner computer and afraid to debug further due to what happened last time.

Is there someone that has any idea what could be happening? How to get around this? 

```
Traceback (most recent call last):
  File "/usr/local/bin/managedtenants", line 5, in <module>
    from managedtenants.cli import main
  File "/usr/local/lib/python3.10/site-packages/managedtenants/cli/__init__.py", line 11, in <module>
    from managedtenants.core.addons_loader import load_addons
  File "/usr/local/lib/python3.10/site-packages/managedtenants/core/addons_loader/__init__.py", line 1, in <module>
    from managedtenants.core.addons_loader.addon import Addon
  File "/usr/local/lib/python3.10/site-packages/managedtenants/core/addons_loader/addon.py", line 26, in <module>
    class UniqueYAMLKeyLoader(yaml.CSafeLoader):
AttributeError: module 'yaml' has no attribute 'CSafeLoader'. Did you mean: 'SafeLoader'?
```

**Comment by cmwylie19** [comment]
Is there a way to build bundle index image without using the cli?
